### ISSUE TITLE
css元素隐藏

### ISSUE THREAD

**Issue by berwin** [berwin/Blog#7]
```css
{ display: none; /* 不占据空间，无法点击 */ }
```
```css
{ visibility: hidden; /* 占据空间，无法点击 */ }
```

```css
{ position: absolute; clip:rect(1px 1px 1px 1px); /* 不占据空间，无法点击 */ }
```

```css
{ position: absolute; top: -999em; /* 不占据空间，无法点击 */ }
```
```css
{ position: relative; top: -999em; /* 占据空间，无法点击 */ }
```
```css
{ position: absolute; visibility: hidden; /* 不占据空间，无法点击 */ }
```
```css
{ height: 0; overflow: hidden; /* 不占据空间，无法点击 */ }
```
```css
{ opacity: 0; filter:Alpha(opacity=0); /* 占据空间，可以点击 */ }
```
```css
{ position: absolute; opacity: 0; filter:Alpha(opacity=0); /* 不占据空间，可以点击 */ }
```
```css
{
    zoom: 0.001;
    -moz-transform: scale(0);
    -webkit-transform: scale(0);
    -o-transform: scale(0);
    transform: scale(0);
    /* IE6/IE7/IE9不占据空间，IE8/FireFox/Chrome/Opera占据空间。都无法点击 */
}
```
```css
{
    position: absolute;
    zoom: 0.001;
    -moz-transform: scale(0);
    -webkit-transform: scale(0);
    -o-transform: scale(0);
    transform: scale(0); 
    /* 不占据空间，无法点击 */
}
```
